# Generated by Django 2.2.2 on 2019-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='related',
            field=models.ManyToManyField(null=True, to='attractions.Attraction'),
        ),
    ]
