# Generated by Django 2.2.2 on 2019-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20190608_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='coor_x',
            field=models.FloatField(editable=False, null=True, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='coor_y',
            field=models.FloatField(editable=False, null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, to='attractions.Attraction'),
        ),
    ]
