# Generated by Django 2.2.2 on 2019-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20190608_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attention',
            field=models.BooleanField(default=False, verbose_name='Attention'),
        ),
    ]
