# Generated by Django 2.2.2 on 2019-06-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_attraction_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='attention',
            field=models.BooleanField(default=True, verbose_name='Attention'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='attractions.Tag'),
        ),
    ]
