# Generated by Django 2.2.2 on 2019-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_auto_20190609_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
