# Generated by Django 2.2.2 on 2019-06-08 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0004_auto_20190608_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattraction',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userattraction',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='userattraction',
            unique_together={('user', 'attraction')},
        ),
    ]
