# Generated by Django 2.2.2 on 2019-06-08 15:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_auto_20190608_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='coor_x',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='coor_y',
        ),
        migrations.AddField(
            model_name='attraction',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
