# Generated by Django 2.2.2 on 2019-06-08 17:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_auto_20190608_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
